#!/usr/bin/env node

/* eslint-disable */

var exec = require('child_process').exec;
var path = require('path');
var fs   = require('fs');

process.stdin.resume();
process.stdin.setEncoding('utf8');

var dir = process.cwd();

cleanRepo(dir, function () {
  installDeps(function(error) {
    if (error) {
      process.stdout.write(error);
    }
    deleteFileInCurrentDir('init', function() {
      initGit(dir, function () {
        process.stdout.write('\nDone.');
        process.exit(0);
      });
    });
  });
});

/**
 * Deletes the .git folder in dir
 */
function cleanRepo(dir, callback) {
  process.stdout.write('\nCleaning old repository...');
  exec('rm -Rf .git/', addCheckMark.bind(null, callback));
}

/**
 * Initializes git again
 */
function initGit(dir, callback) {
  process.stdout.write('\nInitialising new repository...');
  exec('git init && git add . && git commit -m "Initial commit"', addCheckMark.bind(null, callback));
}

/**
 * Deletes a file in the current directory
 */
function deleteFileInCurrentDir(file, callback) {
  fs.unlink(path.join(__dirname, file), callback);
}

/**
 * Installs dependencies
 */
function installDeps(callback) {
  process.stdout.write('\nInstalling dependencies... (This might take a while)')
  exec('npm install', addCheckMark.bind(null, callback));
}

/**
 * Adds mark check symbol
 */
function addCheckMark(callback) {
  process.stdout.write(' ✓');
  callback();
}
