/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

// PostCSS plugins
const cssnext = require('postcss-cssnext');
const postcssFocus = require('postcss-focus');
const postcssReporter = require('postcss-reporter');

const argv = require('minimist')(process.argv.slice(2));
const port = argv.p || 3000;

module.exports = require('./webpack.base.babel')({
  // Add hot reloading in development
  entry: [
    'webpack-dev-server/client?http://localhost:' + port, // Needed for hot reloading
    'webpack/hot/only-dev-server',
    path.join(__dirname, '../..', 'app/app.js'), // Start with js/app.js
  ],
  // Load the CSS in a style tag in development
  cssLoaders: 'style-loader!css-loader?modules&importLoaders=1&sourceMap!postcss-loader',
  // Process the CSS with PostCSS
  postcssPlugins: [
    postcssFocus(), // Add a :focus to every :hover
    cssnext({ // Allow future CSS features to be used, also auto-prefixes the CSS...
      browsers: ['last 2 versions', 'IE > 10'], // ...based on this browser list
    }),
    postcssReporter({ // Posts messages from plugins to the terminal
      clearMessages: true,
    }),
  ],
  // Add hot reloading
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      template: 'app/index.html',
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
    }),
  ],
  // Tell babel that we want to hot-reload
  babelQuery: {
    presets: ['react-hmre'],
  },
  // Emit a source map for easier debugging
  devtool: 'inline-source-map',
});
